### ISSUE TITLE
Arkas DOI points to Artemis

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#1]
There may need to be a new DOI for Arkas.

**Comment by ttriche** [comment]
absolutely -- this is a good thing IMHO

--t

**Comment by arcolombo** [comment]
PR is coming.

**Comment by arcolombo** [comment]
PR points to new arkas Zenodo DOI and build info points to arkas.  the Zenodo  DOI points to Artemis which @ttriche used for EISAI
