### ISSUE TITLE
sra header converti for missing run IDS

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#19]
so sra files have no run Ids e.g.  @SRR892995.2 HWI-ST601:8:1101:1238:2144 length=100
,  putting in a patch to fix this sraheaderconvert.

arkas assumes SRA files have run IDs  e.g  @SRR1564893.1 HWI-ST972:1180:D225DACXX:7:1101:1247:2104 length=50
,  so need to have a flag.

**Comment by arcolombo** [comment]
so to make things even worse  this specific header file 

 @SRR892995.2 HWI-ST601:8:1101:1238:2144 length=100

is missing the lane.   so it seems like the true best solution must give users control to overwrite the header for each column, as opposed to assuming the SRA header has all 10 required columns.  
on my branch I added a boolean to flag if the SRA header has the run ID.  
one solution is to have parameters for Lane number

then this would allow users to select the lane number (could be a dummy), and arkas could force a bogus/dummy run-number and run-ID.

the required columns must be :  @machine:run-number:run-ID:lane:tile-num:xposition:yPosition 1:N:0:1
 so essential the _only_ thing arkas should preserve from SRA is the tile-number, and tile positions.  

sigh.  so frustrating and so stupid. but necessary stupid.   sort of making a simple process more complex than my desires.......

**Comment by ttriche** [comment]
as simple as possible, _but no simpler_

--t

**Comment by arcolombo** [comment]
![thebride](https://cloud.githubusercontent.com/assets/5473099/16964731/dae9983e-4db1-11e6-984e-9531796b10d0.jpg)

okay

**Comment by arcolombo** [comment]
the current patch I have is working handy, just use a single boolean flag, if the flag is true, then it runs a specific shell script which handles a dummy addition of runNumber _and_ runID for this specific use case.  if the flag is false then the runID exists, and _most likely_ the run number does too.  upcoming PR will close this....  mouse data is being uploaded currently.  upload time is not very fast....

**Comment by arcolombo** [comment]
closing due to PR
