### ISSUE TITLE
Annotate Features erroring out on Kexp

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#2]
Received an error on this line in annotateFeatures,  I have a work around to solve this... incoming PR
for my case I am developing of mouse data, have not really explored how arkas works with musc, assumed it would be 1:1.   hitting small bumps.

these are not disjoint sets, but have 80% overlap.    

ebug: feats <- feats[rownames(kexp)]
Browse[2]> 
Error in NSBS(i, x, exact = exact, upperBoundIsStrict = !allow.append) : 
  subscript contains invalid names
In addition: Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

**Comment by arcolombo** [comment]
this error happens when the rownames of a kexp is greater than the feats object.

**Comment by arcolombo** [comment]
Update:  I pushed a change on my branch, if it passes, then I will create a PR.

**Comment by ttriche** [comment]
Hmmm.  I think I've tried to find a graceful, generic solution to this
issue multiple times (i.e. so that an experiment can be progressively
annotated without a requirement to have all rows fully annotated) and I
distinctly remember it being harder than I thought it should have been.
The emptyAnnotation placeholder (or whatever it's called now) was supposed
to be the solution to this problem, but apparently it's not, at least not
yet... :-/

--t

**Comment by ttriche** [comment]
awesome

--t

**Comment by arcolombo** [comment]
In this case, the feats was roughly 10,000 entries, where the actual kexp was 12,000 so the subset error makes sense. 
  if I hit
features(kexp)[names(feats)] <- feats,
this solves the subset issue because the larger set is the parent set.   so this just requires a length check.

so retarded.

**Comment by arcolombo** [comment]
what an elegant solution.  just tested this out on CEL-Seq mouse sample data, and this worked on my data set. more classy then my writing. so I'm closing this.

**Comment by arcolombo** [comment]
@ttriche bug checks for trailing "." in ensembl data, and also finds the missing rows, prints them to screen, and concatenates them into the rolling feats GRanges object if the rownames of the kexp are not all in the rownames of the found annotations.    classy and sleek.
