### ISSUE TITLE
R CMD Check checking dependencies in R code

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#28]
here is one
- checking dependencies in R code ... WARNING
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  Loading required package: biomaRt
  Warning: replacing previous import ‘Biostrings::tail’ by ‘utils::tail’ when loading ‘TxDbLite’
  Warning: replacing previous import ‘Biostrings::head’ by ‘utils::head’ when loading ‘TxDbLite’
  Loading required package: SummarizedExperiment
  Loading required package: Rsamtools
  Loading required package: XVector
  Loading required package: Biostrings
  Loading required package: beeswarm
  Loading required package: tools
  Loading required package: ComplexHeatmap
  Loading required package: grid
  Loading required package: grDevices

Attaching package: ‘ComplexHeatmap’

The following object is masked from ‘package:biomaRt’:

```
select
```

The following object is masked from ‘package:AnnotationDbi’:

```
select
```

Attaching package: ‘arkas’

The following object is masked from ‘package:TxDbLite’:

```
strpop
```

'::' or ':::' import not declared from: ‘BiocGenerics’
'library' or 'require' call not declared from: ‘biomaRt’
'library' or 'require' call to ‘biomaRt’ in package code.
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.
Namespace in Imports field not imported from: ‘Matrix’
  All declared Imports should be used.
Packages in Depends field not imported from:
  ‘SummarizedExperiment’ ‘beeswarm’ ‘ggplot2’ ‘jsonlite’ ‘parallel’
  ‘qusage’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
Unexported objects imported by ':::' calls:
  ‘BiocGenerics:::replaceSlots’
  ‘SummarizedExperiment:::.valid.SummarizedExperiment0.assays_ncol’
  ‘SummarizedExperiment:::.valid.SummarizedExperiment0.assays_nrow’
  See the note in ?`:::` about the use of this operator.
package 'methods' is used but not declared

**Comment by ttriche** [comment]
gah.  May be time to tear out some old SummarizedExperiment compatibility
code now that the release has cleaned it all up

--t

On Tue, Aug 9, 2016 at 3:04 PM, Anthony R. Colombo <notifications@github.com

**Comment by arcolombo** [comment]
can you merge in your PR changes.. ?

**Comment by ttriche** [comment]
sure as soon as I make them :-D

--t

On Tue, Aug 9, 2016 at 3:56 PM, Anthony R. Colombo <notifications@github.com

**Comment by arcolombo** [comment]
why not copy the function replaceSlots into arkas itself?  yes this is generating one's own electricity, but is this a bad approach?

**Comment by ttriche** [comment]
usually it is, yes.... unless we want to start maintaining that generic (we
don't)

--t

**Comment by arcolombo** [comment]
I was able to solve this into a NOTE.  here is the updated check,  then I will put the steps.
- checking dependencies in R code ... NOTE
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  Loading required package: biomaRt
  Warning: replacing previous import ‘Biostrings::tail’ by ‘utils::tail’ when loading ‘TxDbLite’
  Warning: replacing previous import ‘Biostrings::head’ by ‘utils::head’ when loading ‘TxDbLite’
  Loading required package: SummarizedExperiment
  Loading required package: Rsamtools
  Loading required package: XVector
  Loading required package: Biostrings
  Loading required package: beeswarm
  Loading required package: tools
  Loading required package: ComplexHeatmap
  Loading required package: grid
  Loading required package: grDevices

Attaching package: ‘ComplexHeatmap’

The following object is masked from ‘package:biomaRt’:

```
select
```

The following object is masked from ‘package:AnnotationDbi’:

```
select
```

Attaching package: ‘arkas’

The following object is masked from ‘package:GenomicFeatures’:

```
features
```

Namespace in Imports field not imported from: ‘Matrix’
  All declared Imports should be used.
Packages in Depends field not imported from:
  ‘SummarizedExperiment’ ‘beeswarm’ ‘parallel’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
Missing objects imported by ':::' calls:
  ‘SummarizedExperiment:::.valid.SummarizedExperiment.assays_ncol’
  ‘SummarizedExperiment:::.valid.SummarizedExperiment.assays_nrow’
Unexported object imported by a ':::' call: ‘BiocGenerics:::replaceSlots’
  See the note in ?`:::` about the use of this operator.
package 'methods' is used but not declared

steps
1) the first thing is that the packages it previously listed under depends (parallel, Matrix, jsonlite), but not imported, I put into Suggests,  the only package needed was jsonlite, which uses fromJSON in the method fetchAppSession.R.  so I put this into @importFrom tag, and moved the others into suggests changing the DESCRIPTION.
2) Arkas now imports BiocGenerics:: because the check reported that there was an issue  calling ':::' in Kallisto-methods.R without using an import,  so I added it under the import.
3) I changed the SummarizedExperiment0,  to SummarizedExperiment_nrow    because the .valid functions exist in the current SummarizedExperiment, which arkas already imports.  so no more SummarizedExperiment0.

these 3 changes removed this warning into a Note.

for me, my goal is to remove all the warnings and pass the NOTE clean ups to @ttriche.

**Comment by arcolombo** [comment]
so now there are 5 warnings, and 6 notes.  notes are allowed.  warnings are not.

**Comment by arcolombo** [comment]
Correction,  it turns out that you actually need to use the .valid functions from SummarizedExperiment0.

so step 3) was reverted.

**Comment by arcolombo** [comment]
here is an updated check result with latest changes (1 and 2 only)
- checking dependencies in R code ... NOTE
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  Loading required package: biomaRt
  Warning: replacing previous import ‘Biostrings::tail’ by ‘utils::tail’ when loading ‘TxDbLite’
  Warning: replacing previous import ‘Biostrings::head’ by ‘utils::head’ when loading ‘TxDbLite’
  Loading required package: SummarizedExperiment
  Loading required package: Rsamtools
  Loading required package: XVector
  Loading required package: Biostrings
  Loading required package: tools
  Loading required package: ComplexHeatmap
  Loading required package: grid
  Loading required package: grDevices

Attaching package: ‘ComplexHeatmap’

The following object is masked from ‘package:biomaRt’:

```
select
```

The following object is masked from ‘package:AnnotationDbi’:

```
select
```

Attaching package: ‘arkas’
The following object is masked from ‘package:GenomicFeatures’:

```
features
```

Package in Depends field not imported from: ‘SummarizedExperiment’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
Unexported objects imported by ':::' calls:
  ‘BiocGenerics:::replaceSlots’
  ‘SummarizedExperiment:::.valid.SummarizedExperiment0.assays_ncol’
  ‘SummarizedExperiment:::.valid.SummarizedExperiment0.assays_nrow’
  See the note in ?`:::` about the use of this operator.
package 'methods' is used but not declared

**Comment by arcolombo** [comment]
So the current PR from @arcolombo branch solves this issue.  Closing for now.  If any major issues are reported, please re-open this one.  Attached is the updated R check showing that this issue is now a NOTE.

[updatedCheck-5.txt](https://github.com/RamsinghLab/arkas/files/412638/updatedCheck-5.txt)

**Comment by ttriche** [comment]
ah shit, I should have committed my eaarlier changes today.  Basically I
want to get rid of the features and covariates generics and just alias
them, and do this with as many rough edges as we can get away with.  I
started in on that but didn't commit all of it yet :-/

--t

**Comment by arcolombo** [comment]
commit them and ill clean up

**Comment by arcolombo** [comment]
on the other hand, what is the problem with keeping the generics?
