### ISSUE TITLE
CMD check S3 generic/method consistency

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#29]
- checking S3 generic/method consistency ... WARNING
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  Loading required package: biomaRt
  Warning: replacing previous import ‘Biostrings::tail’ by ‘utils::tail’ when loading ‘TxDbLite’
  Warning: replacing previous import ‘Biostrings::head’ by ‘utils::head’ when loading ‘TxDbLite’
  Loading required package: SummarizedExperiment
  Loading required package: Rsamtools
  Loading required package: XVector
  Loading required package: Biostrings
  Loading required package: beeswarm
  Loading required package: tools
  Loading required package: ComplexHeatmap
  Loading required package: grid

Attaching package: ‘ComplexHeatmap’

The following object is masked from ‘package:biomaRt’:

```
select
```

The following object is masked from ‘package:AnnotationDbi’:

```
select
```

Attaching package: ‘arkas’
The following object is masked from ‘package:TxDbLite’:

```
strpop
```

See section ‘Generic functions and methods’ in the ‘Writing R
Extensions’ manual.
- checking replacement functions ... WARNING
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  Loading required package: biomaRt
  Warning: replacing previous import ‘Biostrings::tail’ by ‘utils::tail’ when loading ‘TxDbLite’
  Warning: replacing previous import ‘Biostrings::head’ by ‘utils::head’ when loading ‘TxDbLite’
  Loading required package: SummarizedExperiment
  Loading required package: Rsamtools
  Loading required package: XVector
  Loading required package: Biostrings
  Loading required package: beeswarm
  Loading required package: tools
  Loading required package: ComplexHeatmap
  Loading required package: grid

Attaching package: ‘ComplexHeatmap’

The following object is masked from ‘package:biomaRt’:

```
select
```

The following object is masked from ‘package:AnnotationDbi’:

```
select
```

Attaching package: ‘arkas’

The following object is masked from ‘package:TxDbLite’:

```
strpop
```

The argument of a replacement function which corresponds to the right
hand side must be named ‘value’.

**Comment by ttriche** [comment]
well, I guess we don't need strpop defined in arkas, for starters

--t

On Tue, Aug 9, 2016 at 3:05 PM, Anthony R. Colombo <notifications@github.com

**Comment by arcolombo** [comment]
so I've been looking at this and have observed a few things.

First Ive merged in Tim's master branch ( PR #38 I believe)  and  the features generics are now gone using aliases.

So I've ran the CMD check on Tim's master branch and got the warning:
- checking S3 generic/method consistency ... WARNING
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  See section ‘Generic functions and methods’ in the ‘Writing R
  Extensions’ manual.
- checking replacement functions ... WARNING
  Loading required package: rtracklayer
  Loading required package: knitr
  Loading required package: stringdist
  The argument of a replacement function which corresponds to the right
  hand side must be named ‘value’.

so what I've done to troubleshoot, because I'm not sure about what function/method/generic is causing this warning.   so I've been deleting one generic at a time and re-checking.    Essentially I've deleted Kallisto-Methods entirely and  still get the same WARNING.

then I wiped out the KallistoExperiment-Class  set validity inspector and also removed the .check-assays class function, along with the removal of the Kallisto-methods, and still get the same warning.

updates soon.

**Comment by arcolombo** [comment]
I resolved this one after branching out Tim's PR #38.

Probably some imports need to be declared in the NAMESPACE file.
- checking whether the namespace can be unloaded cleanly ... OK
- checking loading without being on the library search path ... OK
- checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: ‘BiocGenerics’
  All declared Imports should be used.
  Package in Depends field not imported from: ‘SummarizedExperiment’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
  package 'methods' is used but not declared
- checking S3 generic/method consistency ... OK
- checking replacement functions ... OK
- checking foreign function calls ...

**Comment by arcolombo** [comment]
the S3 consistency is O.K,  and the replacement funcitons is O.K.

what a weird puzzle.    
- checking PDF version of manual ... OK
- DONE

Status: 2 WARNINGs, 5 NOTEs
See
  ‘/home/arcolombo/Documents/github_repos/arkas.Rcheck/00check.log’
for details.
