### ISSUE TITLE
R CMD check KallistoExperiment-Methods  'features'

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#30]
this is a tricky one, it pertains to the KallistoExperiment-method for features generic and replacement method.

 checking whether package ‘arkas’ can be installed ... WARNING
Found the following significant warnings:
  Warning: For function ‘features’, signature ‘SummarizedExperiment0’: argument in method definition changed from (object) to (x)
See ‘/home/arcolombo/Documents/github_repos/arkas.Rcheck/00install.out’ for details.

**Comment by ttriche** [comment]
this is an easy fix, just change the method signature for features() in
KallistoExperiment-methods.R

--t

On Tue, Aug 9, 2016 at 6:19 PM, Anthony R. Colombo <notifications@github.com

**Comment by arcolombo** [comment]
solved this one.  consider this toilet unplugged.
