### ISSUE TITLE
alias for covariates and features

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#37]
so if we import GenomicFeatures, can we delete the features generics from Kallisto-metohds?

**Comment by arcolombo** [comment]
essentially we just need to import the covariates and features  generics and methods correct?  again this is a well documented issue that I would like to look into...

**Comment by ttriche** [comment]
That's what I'm thinking.  Dump the covariates generic which we rarely use
anyways, and inherit features() from GenomicFeatures.

--t

**Comment by arcolombo** [comment]
do you suggest this for both KallistoExperiment-methods.R and
Summarized-Experiment.methods?

it does seem sensible to just import GenomicFeatures, and not use the
generics...   thougts?

**Comment by ttriche** [comment]
that.

I should commit my changes now but I have some figures to finish.  I will
sync up your commits to HEAD, and if they don't require too much merging,
I'll push mine up after.  Or if they do, I may blow away my repo and just
re-fork HEAD ;-)

--t

**Comment by arcolombo** [comment]
ok. i have not merged to head and am branching off.

**Comment by ttriche** [comment]
that will lead to merge horror I fear :-/

--t

**Comment by arcolombo** [comment]
ok. I found a great write-up on R OOP and S4 Inheritance.  this is a somewhat easy problem to solve just need a little background.. FYI.
