### ISSUE TITLE
arkas::rowRanges is not compatible with GenomicFeatures::rowRanges

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/arkas#42]
if you use library(matrixStats)  this will over-write the arkas namespace of rowRanges, and thus rowRanges(arkas.kexp)  will fail
 Argument 'x' must be a matrix or a vector.

GenomicFeatures  use of rowRanges is not compatible with arkas::rowRanges for sum reasons

**Comment by ttriche** [comment]
I think we have to explicitly namespace matrixStats::rowRanges()

At  some point I started habitually doing so, as with
igraph::graph.data.frame().  It may be worthwhile for BiocGenerics to
register a rowRanges generic and promote matrixStats' function thusly

--t

**Comment by arcolombo** [comment]
yes that how I was able to solve using your byMads, with a specific call.

so if someone , a general user,  calls library(matrixStats) and it blows
out arkas<SummarizedExperiment::rowRanges,  is this our problem?

**Comment by ttriche** [comment]
no it is not, not any more than it's Marc Carlson's problem when it blows
away GenomicFeatures' rowRanges method :-)

--t
